name: Deploy Automation Account and Sigma2SentinelAutomation runbook

on:
  push:
    branches:
    - "main"
  workflow_dispatch:

env:
  
  AZURE_RESOURCEGROUP_NAME: 'sentinel'
  AUTOMATION_ACCOUNT_NAME: 'SentinelAutomationTest'

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        # Checkout code
      - name : Checkout code
        uses: actions/checkout@v3

        # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.JEREMY_PROD }}
          enable-AzPSSession: true
        
        # Deploy arm template
      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.JEREMY_PROD_SUBSCRIPTION }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: './templates/automationAccount.json'
          parameters: automationAccountName=${{ env.AUTOMATION_ACCOUNT_NAME }}
      
          # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs }}

        # Import runnbooks
      - name: Import runbook scripts
        uses: azure/powershell@v2
        with:
          inlineScript: ./ps/Import-AutomationRunbooks.ps1 -resourceGroupName ${{ env.AZURE_RESOURCEGROUP_NAME }} 
            -automationAccountName ${{ env.AUTOMATION_ACCOUNT_NAME }} -Path ../Runbooks
          azPSVersion: "latest"


