name: Deploy Automation Account and Sigma2SentinelAutomation runbook

on:
  push:
    branches:
    - "main"

env:
  AZURE_RESOURCEGROUP_NAME: 'rd-airs-prd-aue-001'
  AZURE_STORAGE_NAME: 'jeremyhagantest'

jobs:
    build-and-deploy:
      runs-on: windows-latest
